//! Compilation tests — verify that all generated proto types are accessible
//! and the crate builds cleanly with the expected module structure.

#[cfg(test)]
mod compilation_tests {
    use crate::{auth, common, experiments, flags, sdk, segments};

    // ── Existing SDK-facing types ─────────────────────────────────────────────

    #[test]
    fn common_types_accessible() {
        let _: Option<common::v1::Context> = None;
        let _: Option<common::v1::ParameterValue> = None;
    }

    #[test]
    fn flag_sync_types_accessible() {
        let _: Option<flags::v1::FeatureFlag> = None;
        let _: Option<flags::v1::SyncRequest> = None;
        let _: Option<flags::v1::SyncResponse> = None;
        let _: Option<flags::v1::Variant> = None;
        let _: Option<flags::v1::FlagRule> = None;
    }

    #[test]
    fn segment_types_accessible() {
        let _: Option<segments::v1::RuleSegment> = None;
        let _: Option<segments::v1::ListSegment> = None;
        let _: Option<segments::v1::SegmentBundle> = None;
    }

    // ── New microservice contracts ─────────────────────────────────────────────

    #[test]
    fn auth_service_types_accessible() {
        let _: Option<auth::v1::CredentialRequest> = None;
        let _: Option<auth::v1::RbacContext> = None;
    }

    #[test]
    fn flag_service_types_accessible() {
        let _: Option<flags::v1::GetFlagRequest> = None;
        let _: Option<flags::v1::ListFlagsRequest> = None;
        let _: Option<flags::v1::ListFlagsResponse> = None;
        let _: Option<flags::v1::MutateFlagRequest> = None;
        let _: Option<flags::v1::MutateFlagResponse> = None;
        let _: Option<flags::v1::GetFlagDefinitionsRequest> = None;
    }

    #[test]
    fn segmentation_service_types_accessible() {
        let _: Option<segments::v1::GetSegmentRequest> = None;
        let _: Option<segments::v1::ListSegmentsRequest> = None;
        let _: Option<segments::v1::ListSegmentsResponse> = None;
        let _: Option<segments::v1::EvaluateMembershipRequest> = None;
        let _: Option<segments::v1::EvaluateMembershipResponse> = None;
        let _: Option<segments::v1::MutateSegmentRequest> = None;
        let _: Option<segments::v1::MutateSegmentResponse> = None;
    }

    #[test]
    fn experimentation_service_types_accessible() {
        let _: Option<experiments::v1::Experiment> = None;
        let _: Option<experiments::v1::ExperimentResults> = None;
        let _: Option<experiments::v1::CreateExperimentRequest> = None;
        let _: Option<experiments::v1::GetExperimentRequest> = None;
        let _: Option<experiments::v1::ListExperimentsRequest> = None;
        let _: Option<experiments::v1::ListExperimentsResponse> = None;
        let _: Option<experiments::v1::GetResultsRequest> = None;
    }

    // ── SDK contracts (sdks/spec/proto/sdk/v1/) ─────────────────────────────

    #[test]
    fn sdk_service_messages_accessible() {
        let _: Option<sdk::v1::SyncDefinitionsRequest> = None;
        let _: Option<sdk::v1::SyncDefinitionsResponse> = None;
        let _: Option<sdk::v1::IngestSdkEvalLogRequest> = None;
        let _: Option<sdk::v1::IngestSdkEvalLogResponse> = None;
        let _: Option<sdk::v1::FlagEvaluationEvent> = None;
    }

    #[test]
    fn sdk_service_client_and_server_stubs_generated() {
        // Both client and server stubs should be generated by tonic_build.
        // If these typedefs compile, both halves of the gRPC contract exist.
        type _GatewayClient<T> = sdk::v1::sdk_service_client::SdkServiceClient<T>;
        type _GatewayServer<T> = sdk::v1::sdk_service_server::SdkServiceServer<T>;
        type _FlagBackendClient<T> =
            sdk::v1::flag_sdk_backend_service_client::FlagSdkBackendServiceClient<T>;
        type _FlagBackendServer<T> =
            sdk::v1::flag_sdk_backend_service_server::FlagSdkBackendServiceServer<T>;
        type _SegBackendClient<T> =
            sdk::v1::segmentation_sdk_backend_service_client::SegmentationSdkBackendServiceClient<
                T,
            >;
        type _SegBackendServer<T> =
            sdk::v1::segmentation_sdk_backend_service_server::SegmentationSdkBackendServiceServer<
                T,
            >;
    }

    #[test]
    fn sdk_backend_messages_accessible() {
        let _: Option<sdk::v1::BatchCheckListMembershipRequest> = None;
        let _: Option<sdk::v1::BatchCheckListMembershipResponse> = None;
        let _: Option<sdk::v1::MembershipQuery> = None;
        let _: Option<sdk::v1::MembershipResult> = None;
    }
}
