[package]
name = "stitchd-sdk"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dev-dependencies]
stitchd-db = { path = "../stitchd-db" }
sqlx = { workspace = true }
chrono = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
axum = { workspace = true }
tokio-stream = { version = "0.1", features = ["net"] }
tower = { version = "0.5", features = ["util"] }
wiremock = { version = "0.6" }

[dependencies]
stitchd-core = { path = "../stitchd-core" }
stitchd-proto = { path = "../stitchd-proto" }
tonic = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
