[package]
name = "stitchd-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[features]
openapi = ["dep:utoipa"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
semver = { workspace = true }
smallvec = { workspace = true }
async-trait = { workspace = true }
siphasher = { workspace = true }
sqlx = { workspace = true }
murmur3 = { workspace = true }
utoipa = { workspace = true, optional = true }
aes-gcm = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
jsonwebtoken = { workspace = true }
sha2 = { workspace = true }
