//! OTP (one-time-password) repository for password resets.
//!
//! The raw 6-digit code is generated by [`stitchd_core::auth::crypto::generate_otp`].
//! Only the Argon2id hash is stored in the database.

use async_trait::async_trait;
use chrono::{Duration, Utc};
use sqlx::PgPool;

use crate::RepositoryError;

// ---------------------------------------------------------------------------
// Trait
// ---------------------------------------------------------------------------

/// Operations on the `password_reset_otps` table.
#[async_trait]
pub trait OtpRepository: Send + Sync {
    /// Create a new OTP for `email` with a 10-minute TTL.
    ///
    /// Returns `(record_id, raw_otp_code)`.  The raw code must be delivered to
    /// the user (e.g. via email); only the Argon2id hash is stored.
    async fn create(&self, email: &str) -> Result<(uuid::Uuid, String), RepositoryError>;

    /// Find a valid (non-expired, non-used) OTP record by email.
    ///
    /// Returns `Some((id, otp_hash))` so the caller can verify the submitted code.
    /// Returns `None` if no valid OTP exists.
    async fn find_valid_by_email(
        &self,
        email: &str,
    ) -> Result<Option<(uuid::Uuid, String)>, RepositoryError>;

    /// Mark an OTP record as consumed by setting `used_at = now()`.
    async fn consume(&self, id: uuid::Uuid) -> Result<(), RepositoryError>;
}

// ---------------------------------------------------------------------------
// Postgres implementation
// ---------------------------------------------------------------------------

/// Postgres-backed [`OtpRepository`].
pub struct PgOtpRepository {
    /// Shared Postgres connection pool.
    pub pool: PgPool,
}

impl PgOtpRepository {
    /// Construct a new repository bound to `pool`.
    #[must_use]
    pub const fn new(pool: PgPool) -> Self {
        Self { pool }
    }
}

#[async_trait]
impl OtpRepository for PgOtpRepository {
    async fn create(&self, email: &str) -> Result<(uuid::Uuid, String), RepositoryError> {
        let (raw_otp, otp_hash) = stitchd_core::auth::crypto::generate_otp();
        let expires_at = Utc::now() + Duration::minutes(10);

        let row = sqlx::query!(
            r#"
            INSERT INTO password_reset_otps (email, otp_hash, expires_at)
            VALUES ($1, $2, $3)
            RETURNING id
            "#,
            email,
            otp_hash,
            expires_at,
        )
        .fetch_one(&self.pool)
        .await
        .map_err(RepositoryError::Database)?;

        Ok((row.id, raw_otp))
    }

    async fn find_valid_by_email(
        &self,
        email: &str,
    ) -> Result<Option<(uuid::Uuid, String)>, RepositoryError> {
        let row = sqlx::query!(
            r#"
            SELECT id, otp_hash
            FROM password_reset_otps
            WHERE email = $1
              AND expires_at > now()
              AND used_at IS NULL
            ORDER BY created_at DESC
            LIMIT 1
            "#,
            email,
        )
        .fetch_optional(&self.pool)
        .await
        .map_err(RepositoryError::Database)?;

        Ok(row.map(|r| (r.id, r.otp_hash)))
    }

    async fn consume(&self, id: uuid::Uuid) -> Result<(), RepositoryError> {
        let affected = sqlx::query!(
            r#"
            UPDATE password_reset_otps
            SET used_at = now()
            WHERE id = $1 AND used_at IS NULL
            "#,
            id,
        )
        .execute(&self.pool)
        .await
        .map_err(RepositoryError::Database)?
        .rows_affected();

        if affected == 0 {
            return Err(RepositoryError::NotFound { id: id.to_string() });
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Integration tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[sqlx::test(migrations = "./migrations")]
    async fn create_returns_id_and_raw_otp(pool: PgPool) {
        let repo = PgOtpRepository::new(pool);
        let (id, raw_otp) = repo.create("alice@example.com").await.unwrap();
        assert!(!id.is_nil());
        assert_eq!(raw_otp.len(), 6);
        assert!(raw_otp.chars().all(|c| c.is_ascii_digit()));
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn find_valid_by_email_returns_recent_otp(pool: PgPool) {
        let repo = PgOtpRepository::new(pool);
        let (id, _) = repo.create("bob@example.com").await.unwrap();
        let found = repo.find_valid_by_email("bob@example.com").await.unwrap();
        assert!(found.is_some());
        assert_eq!(found.unwrap().0, id);
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn consume_marks_otp_used(pool: PgPool) {
        let repo = PgOtpRepository::new(pool);
        let (id, _) = repo.create("carol@example.com").await.unwrap();
        repo.consume(id).await.unwrap();
        let found = repo.find_valid_by_email("carol@example.com").await.unwrap();
        assert!(found.is_none());
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn expired_otp_not_returned(pool: PgPool) {
        let repo = PgOtpRepository::new(pool.clone());
        // Insert an already-expired OTP directly
        sqlx::query!(
            r#"
            INSERT INTO password_reset_otps (email, otp_hash, expires_at)
            VALUES ($1, $2, now() - interval '1 minute')
            "#,
            "dave@example.com",
            "somehash",
        )
        .execute(&pool)
        .await
        .unwrap();

        let found = repo.find_valid_by_email("dave@example.com").await.unwrap();
        assert!(found.is_none());
    }
}
