//! Refresh token repository — trait definition and Postgres implementation.
//!
//! Raw tokens are generated by [`stitchd_core::auth::crypto::generate_opaque_token`].
//! Only the SHA-256 hash is stored; the raw value is returned to the caller once.

use async_trait::async_trait;
use chrono::{Duration, Utc};
use sqlx::PgPool;
use stitchd_core::{
    auth::{RefreshToken, RefreshTokenId, UserId, crypto::generate_opaque_token},
    id::OrganisationId,
};

use crate::RepositoryError;

/// Operations on [`RefreshToken`] records.
#[async_trait]
pub trait RefreshTokenRepository: Send + Sync {
    /// Create a new refresh token for `user_id` in `org_id`.
    ///
    /// Returns `(token, raw_hex)` where:
    /// - `token` is the persisted [`RefreshToken`] (with hash stored in DB).
    /// - `raw_hex` is the one-time raw token to hand back to the client.
    async fn create(
        &self,
        user_id: UserId,
        org_id: OrganisationId,
        device_hint: Option<&str>,
        ttl_days: i64,
    ) -> Result<(RefreshToken, String), RepositoryError>;

    /// Find an active (non-revoked, non-expired) token by its SHA-256 hash.
    async fn find_by_hash(&self, hash: &str) -> Result<Option<RefreshToken>, RepositoryError>;

    /// Consume a token (set `revoked_at` to now) and return it.
    ///
    /// Returns `None` if the token does not exist.
    async fn consume(&self, id: RefreshTokenId) -> Result<Option<RefreshToken>, RepositoryError>;

    /// Revoke a token by ID (sets `revoked_at = now()`).
    async fn revoke(&self, id: RefreshTokenId) -> Result<(), RepositoryError>;

    /// Revoke all tokens belonging to `user_id`.
    async fn revoke_all_for_user(&self, user_id: UserId) -> Result<(), RepositoryError>;

    /// List all active (non-revoked, non-expired) tokens for `user_id`.
    async fn list_active(&self, user_id: UserId) -> Result<Vec<RefreshToken>, RepositoryError>;
}

/// Postgres-backed [`RefreshTokenRepository`].
pub struct PgRefreshTokenRepository {
    /// Shared Postgres connection pool.
    pub pool: PgPool,
}

impl PgRefreshTokenRepository {
    /// Construct a new repository bound to `pool`.
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }
}

#[async_trait]
impl RefreshTokenRepository for PgRefreshTokenRepository {
    async fn create(
        &self,
        user_id: UserId,
        org_id: OrganisationId,
        device_hint: Option<&str>,
        ttl_days: i64,
    ) -> Result<(RefreshToken, String), RepositoryError> {
        let (raw_hex, token_hash) = generate_opaque_token();
        let now = Utc::now();
        let expires_at = now + Duration::days(ttl_days);

        let row = sqlx::query!(
            r#"
            INSERT INTO refresh_tokens
                (user_id, org_id, token_hash, device_hint, issued_at, expires_at)
            VALUES ($1, $2, $3, $4, $5, $6)
            RETURNING
                id,
                user_id,
                org_id,
                token_hash,
                device_hint,
                issued_at,
                expires_at,
                revoked_at,
                last_used_at
            "#,
            user_id.as_uuid(),
            org_id.as_uuid(),
            token_hash,
            device_hint,
            now,
            expires_at,
        )
        .fetch_one(&self.pool)
        .await
        .map_err(|e| {
            if let sqlx::Error::Database(ref dbe) = e {
                if let Some(constraint) = dbe.constraint() {
                    return RepositoryError::UniqueViolation {
                        field: constraint.to_string(),
                    };
                }
            }
            RepositoryError::Database(e)
        })?;

        let token = RefreshToken {
            id: RefreshTokenId::from_uuid(row.id),
            user_id: UserId::from_uuid(row.user_id),
            org_id: OrganisationId::from_uuid(row.org_id),
            token_hash: row.token_hash,
            device_hint: row.device_hint,
            issued_at: row.issued_at,
            expires_at: row.expires_at,
            revoked_at: row.revoked_at,
            last_used_at: row.last_used_at,
        };

        Ok((token, raw_hex))
    }

    async fn find_by_hash(&self, hash: &str) -> Result<Option<RefreshToken>, RepositoryError> {
        let row = sqlx::query!(
            r#"
            SELECT
                id,
                user_id,
                org_id,
                token_hash,
                device_hint,
                issued_at,
                expires_at,
                revoked_at,
                last_used_at
            FROM refresh_tokens
            WHERE token_hash = $1
              AND revoked_at IS NULL
              AND expires_at > now()
            "#,
            hash,
        )
        .fetch_optional(&self.pool)
        .await
        .map_err(RepositoryError::Database)?;

        Ok(row.map(|r| RefreshToken {
            id: RefreshTokenId::from_uuid(r.id),
            user_id: UserId::from_uuid(r.user_id),
            org_id: OrganisationId::from_uuid(r.org_id),
            token_hash: r.token_hash,
            device_hint: r.device_hint,
            issued_at: r.issued_at,
            expires_at: r.expires_at,
            revoked_at: r.revoked_at,
            last_used_at: r.last_used_at,
        }))
    }

    async fn consume(&self, id: RefreshTokenId) -> Result<Option<RefreshToken>, RepositoryError> {
        let row = sqlx::query!(
            r#"
            UPDATE refresh_tokens
            SET revoked_at = now()
            WHERE id = $1 AND revoked_at IS NULL
            RETURNING
                id,
                user_id,
                org_id,
                token_hash,
                device_hint,
                issued_at,
                expires_at,
                revoked_at,
                last_used_at
            "#,
            id.as_uuid(),
        )
        .fetch_optional(&self.pool)
        .await
        .map_err(RepositoryError::Database)?;

        Ok(row.map(|r| RefreshToken {
            id: RefreshTokenId::from_uuid(r.id),
            user_id: UserId::from_uuid(r.user_id),
            org_id: OrganisationId::from_uuid(r.org_id),
            token_hash: r.token_hash,
            device_hint: r.device_hint,
            issued_at: r.issued_at,
            expires_at: r.expires_at,
            revoked_at: r.revoked_at,
            last_used_at: r.last_used_at,
        }))
    }

    async fn revoke(&self, id: RefreshTokenId) -> Result<(), RepositoryError> {
        sqlx::query!(
            r#"UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1"#,
            id.as_uuid(),
        )
        .execute(&self.pool)
        .await
        .map_err(RepositoryError::Database)?;
        Ok(())
    }

    async fn revoke_all_for_user(&self, user_id: UserId) -> Result<(), RepositoryError> {
        sqlx::query!(
            r#"
            UPDATE refresh_tokens
            SET revoked_at = now()
            WHERE user_id = $1 AND revoked_at IS NULL
            "#,
            user_id.as_uuid(),
        )
        .execute(&self.pool)
        .await
        .map_err(RepositoryError::Database)?;
        Ok(())
    }

    async fn list_active(&self, user_id: UserId) -> Result<Vec<RefreshToken>, RepositoryError> {
        let rows = sqlx::query!(
            r#"
            SELECT
                id,
                user_id,
                org_id,
                token_hash,
                device_hint,
                issued_at,
                expires_at,
                revoked_at,
                last_used_at
            FROM refresh_tokens
            WHERE user_id = $1
              AND revoked_at IS NULL
              AND expires_at > now()
            ORDER BY issued_at DESC
            "#,
            user_id.as_uuid(),
        )
        .fetch_all(&self.pool)
        .await
        .map_err(RepositoryError::Database)?;

        Ok(rows
            .into_iter()
            .map(|r| RefreshToken {
                id: RefreshTokenId::from_uuid(r.id),
                user_id: UserId::from_uuid(r.user_id),
                org_id: OrganisationId::from_uuid(r.org_id),
                token_hash: r.token_hash,
                device_hint: r.device_hint,
                issued_at: r.issued_at,
                expires_at: r.expires_at,
                revoked_at: r.revoked_at,
                last_used_at: r.last_used_at,
            })
            .collect())
    }
}

// ---------------------------------------------------------------------------
// sqlx::test integration tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: create a minimal org and user in the DB, return (org_id, user_id).
    async fn seed_user(pool: &PgPool) -> (OrganisationId, UserId) {
        let org_id = OrganisationId::new();
        sqlx::query!(
            "INSERT INTO organisations (id, name) VALUES ($1, $2)",
            org_id.as_uuid(),
            "test-org"
        )
        .execute(pool)
        .await
        .unwrap();

        let user_id = UserId::new();
        sqlx::query!(
            r#"INSERT INTO users (id, email, display_name) VALUES ($1, $2, $3)"#,
            user_id.as_uuid(),
            format!("user-{}@example.com", user_id),
            "Test User"
        )
        .execute(pool)
        .await
        .unwrap();

        // Add org membership so FK on refresh_tokens is satisfied
        sqlx::query!(
            "INSERT INTO org_memberships (user_id, org_id, role) VALUES ($1, $2, 'org_member')",
            user_id.as_uuid(),
            org_id.as_uuid(),
        )
        .execute(pool)
        .await
        .unwrap();

        (org_id, user_id)
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn create_returns_raw_token(pool: PgPool) {
        let repo = PgRefreshTokenRepository::new(pool.clone());
        let (org_id, user_id) = seed_user(&pool).await;

        let (token, raw) = repo
            .create(user_id, org_id, Some("desktop"), 30)
            .await
            .unwrap();

        assert!(!raw.is_empty());
        assert_eq!(raw.len(), 64); // 32 bytes hex
        assert_ne!(raw, token.token_hash);
        assert_eq!(token.user_id, user_id);
        assert_eq!(token.org_id, org_id);
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn find_by_hash_finds_active_token(pool: PgPool) {
        let repo = PgRefreshTokenRepository::new(pool.clone());
        let (org_id, user_id) = seed_user(&pool).await;

        let (token, _raw) = repo.create(user_id, org_id, None, 30).await.unwrap();
        let found = repo.find_by_hash(&token.token_hash).await.unwrap();

        assert!(found.is_some());
        assert_eq!(found.unwrap().id, token.id);
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn find_by_hash_returns_none_for_unknown(pool: PgPool) {
        let repo = PgRefreshTokenRepository::new(pool.clone());
        let found = repo.find_by_hash("notarealhash").await.unwrap();
        assert!(found.is_none());
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn consume_sets_revoked_at(pool: PgPool) {
        let repo = PgRefreshTokenRepository::new(pool.clone());
        let (org_id, user_id) = seed_user(&pool).await;

        let (token, _) = repo.create(user_id, org_id, None, 30).await.unwrap();
        assert!(token.revoked_at.is_none());

        let consumed = repo.consume(token.id).await.unwrap().unwrap();
        assert!(consumed.revoked_at.is_some());
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn consume_already_revoked_returns_none(pool: PgPool) {
        let repo = PgRefreshTokenRepository::new(pool.clone());
        let (org_id, user_id) = seed_user(&pool).await;

        let (token, _) = repo.create(user_id, org_id, None, 30).await.unwrap();
        repo.revoke(token.id).await.unwrap();

        let second_consume = repo.consume(token.id).await.unwrap();
        assert!(second_consume.is_none());
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn revoke_all_for_user_revokes_all(pool: PgPool) {
        let repo = PgRefreshTokenRepository::new(pool.clone());
        let (org_id, user_id) = seed_user(&pool).await;

        repo.create(user_id, org_id, Some("desktop"), 30)
            .await
            .unwrap();
        repo.create(user_id, org_id, Some("mobile"), 30)
            .await
            .unwrap();

        repo.revoke_all_for_user(user_id).await.unwrap();

        let active = repo.list_active(user_id).await.unwrap();
        assert!(active.is_empty());
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn list_active_excludes_revoked(pool: PgPool) {
        let repo = PgRefreshTokenRepository::new(pool.clone());
        let (org_id, user_id) = seed_user(&pool).await;

        let (t1, _) = repo.create(user_id, org_id, Some("a"), 30).await.unwrap();
        let (_t2, _) = repo.create(user_id, org_id, Some("b"), 30).await.unwrap();

        repo.revoke(t1.id).await.unwrap();

        let active = repo.list_active(user_id).await.unwrap();
        assert_eq!(active.len(), 1);
        assert_eq!(active[0].device_hint.as_deref(), Some("b"));
    }

    #[sqlx::test(migrations = "./migrations")]
    async fn list_active_excludes_expired(pool: PgPool) {
        let repo = PgRefreshTokenRepository::new(pool.clone());
        let (org_id, user_id) = seed_user(&pool).await;

        // Insert an already-expired token directly
        let (_, _raw) = repo.create(user_id, org_id, Some("active"), 30).await.unwrap();

        // Manually insert an expired token
        sqlx::query!(
            r#"
            INSERT INTO refresh_tokens (user_id, org_id, token_hash, issued_at, expires_at)
            VALUES ($1, $2, $3, now() - interval '2 days', now() - interval '1 day')
            "#,
            user_id.as_uuid(),
            org_id.as_uuid(),
            "expired_token_hash_placeholder"
        )
        .execute(&pool)
        .await
        .unwrap();

        let active = repo.list_active(user_id).await.unwrap();
        // Only the non-expired token should appear
        assert_eq!(active.len(), 1);
        assert_eq!(active[0].device_hint.as_deref(), Some("active"));
    }
}
